Models/Customer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mercuryshop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.DonHangs = new HashSet<DonHang>();
        }
    
        public int Customer_Id { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Email { get; set; }
        public string Customer_Password { get; set; }
        public string Customer_Phone { get; set; }
        public string Customer_Address { get; set; }
        public string Customer_City { get; set; }
        public string Customer_Province { get; set; }
        public Nullable<int> FailedLoginAttempts { get; set; }
        public Nullable<System.DateTime> LockoutEndTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHang> DonHangs { get; set; }
    }
}

Areas/Admin/Controllers/UserAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using Mercuryshop.Models;
using Mercuryshop.Areas.Admin;

namespace Mercuryshop.Areas.Admin.Controllers
{
    public class UserAdminController : Controller
    {
        MecuryshopEntities db = new MecuryshopEntities();
        // GET: Admin/UserAdmin
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult DangNhap()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangNhap(FormCollection collection)
        {
            var sTenDN = collection["Email"];
            var sMatKhau = collection["Pass"];
            if (String.IsNullOrEmpty(sTenDN))
            {
                ViewData["Err1"] = "Bạn chưa nhập tên đăng nhập";
            }
            else if (String.IsNullOrEmpty(sMatKhau))
            {
                ViewData["Err2"] = "Phải nhập mật khẩu";
            }
            else
            {
                ADMIN kh = db.ADMINs.SingleOrDefault(n => n.Email == sTenDN && n.Pass == sMatKhau);
                if (kh != null)
                {
                    ViewBag.ThongBao = "Chúc mừng đăng nhập thành công";
                    Session["TaiKhoan"] = kh;
                    return RedirectToAction("Index", "HomeAdmin");
                }
                else
                {
                    ViewBag.ThongBao = "Tên đăng nhập hoặc mật khẩu không đúng";
                }
            }
            return View();
        }
    }
}

Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mercuryshop.Models;
using System.Data.Entity;
using System.Net.Mail;

namespace Mercuryshop.Controllers
{
    public class CustomerController : Controller
    {
        MecuryshopEntities db = new MecuryshopEntities();
        [HttpGet]
        public ActionResult DangKy()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DangKy(FormCollection collection, Customer kh)
        {
            var sHoTen = collection["Name"];
            var sMatKhau = collection["Pass"];
            var sNhapLaiMK = collection["rePass"];
            var sDiaChi = collection["Address"];
            var sEmail = collection["Email"];
            var sDienThoai = collection["Numberphone"];
            if (String.IsNullOrEmpty(sHoTen))
            {
                ViewData["err1"] = "Họ tên không được rỗng";
            }
            else if (String.IsNullOrEmpty(sMatKhau))
            {
                ViewData["err2"] = "Phải nhập mật khẩu";
            }
            else if (String.IsNullOrEmpty(sNhapLaiMK))
            {
                ViewData["err2"] = "Phải nhập lại mật khẩu";
            }
            else if (sMatKhau != sNhapLaiMK)
            {
                ViewData[""] = "Mật khẩu nhập lại không khớp";
            }
            else if (String.IsNullOrEmpty(sEmail))
            {
                ViewData["err2"] = "Email không được rỗng";
            }
            else if (String.IsNullOrEmpty(sDienThoai))
            {
                ViewData["err2"] = "Số điện thoại không được rỗng";
            }
            else if (db.Customers.SingleOrDefault(n => n.Customer_Email == sEmail) != null)
            {
                ViewBag.ThongBao = "Email đã được sử dụng";
            }
            else
            {
                kh.Customer_Id = 0;
                kh.Customer_Name = sHoTen;
                kh.Customer_Password = sMatKhau;
                kh.Customer_Email = sEmail;
                kh.Customer_Address = sDiaChi;
                kh.Customer_Phone = sDienThoai;
                db.Customers.Add(kh);
                db.SaveChanges();
                return RedirectToAction("DangNhap");
            }
            return this.DangKy();
        }

        [HttpGet]
        public ActionResult DangNhap()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangNhap(FormCollection collection)
        {
            var sTenDN = collection["Email"];
            var sMatKhau = collection["Pass"];
            if (String.IsNullOrEmpty(sTenDN))
            {
                ViewData["Err1"] = "Bạn chưa nhập tên đăng nhập";
            }
            else if (String.IsNullOrEmpty(sMatKhau))
            {
                ViewData["Err2"] = "Phải nhập mật khẩu";
            }
            else
            {
                Customer kh = db.Customers.SingleOrDefault(n => n.Customer_Email == sTenDN && n.Customer_Password == sMatKhau);
                if (kh != null)
                {
                    ViewBag.ThongBao = "Chúc mừng đăng nhập thành công";
                    Session["TaiKhoan"] = kh;
                    return RedirectToAction("Index", "Mercuryshop");
                }
                else
                {
                    ViewBag.ThongBao = "Tên đăng nhập hoặc mật khẩu không đúng";
                }
            }
            return View();
        }
        public ActionResult logout()
        {
            if(Session["Customers"] != null)
            {
                //Session["NameCustomers"] = null;
                Session["Customers"] = null;
            }
            return RedirectToAction("Index", "Mercuryshop");
        }

        // GET: Customer
        public ActionResult Index()
        {
            return View();
        }

        // Dat lai mk
        [HttpGet]
        public ActionResult ResetPW()
        {
            return View();
        }

        [HttpPost]
        public ActionResult resetPW()
        {
            return View();
        }


        [HttpGet]
        public ActionResult RequestResetPX()
        {
            return View();
        }
        [HttpPost]
        public ActionResult RequestResetPX(FormCollection collection)
        {
            var sEmail = collection["Email"];
            Customer TK = db.Customers.SingleOrDefault(n => n.Customer_Email == sEmail);
            if (TK != null)
            {
                ViewBag.ThongBao = "1";
                MailMessage mail = new MailMessage();
                mail.To.Add("testwebpbshop@gmail.com");
                mail.From = new MailAddress("testwebpbshop@gmail.com");
                mail.Subject = "Đặt lại mật khẩu";
                string Body = "Bấm vào đây để <a href='https://localhost:44364/User/ResetPW'>Đặt lại mật Khẩu</a>";
                mail.Body = Body;
                mail.IsBodyHtml = true;
                SmtpClient smtp = new SmtpClient();
                smtp.Host = "smtp.gmail.com";
                smtp.Port = 587;
                smtp.UseDefaultCredentials = false;
                smtp.Credentials = new System.Net.NetworkCredential("testwebpbshop@gmail.com", "zldo aupo wkff mqvi"); // Enter seders User name and password       
                smtp.EnableSsl = true;
                smtp.Send(mail);
            }
            else
            {
                ViewBag.ThongBao = " ";
            }

            return View();
        }
    }
}

Controllers/ShopCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mercuryshop.Models;
using System.Data.Entity;

namespace Mercuryshop.Controllers
{
    public class ShopCartController : Controller
    {
        MecuryshopEntities db = new MecuryshopEntities();
        public List<Cart> LayGioHang()
        {
            List<Cart> lstGioHang = Session["Cart"] as List<Cart>;
            if (lstGioHang == null)
            {
                lstGioHang = new List<Cart>();
                Session["Cart"] = lstGioHang;
            }
            return lstGioHang;
        }

        public ActionResult ThemGioHang(int ms, string url)
        {
            if(Session["TaiKhoan"]==null)
            {
                return RedirectToAction("DangNhap","Customer");
            }
            else
            {
                List<Cart> lstGioHang = LayGioHang();
                Cart sp = lstGioHang.Find(n => n.iMasp == ms);
                if (sp == null)
                {
                    sp = new Cart(ms);
                    lstGioHang.Add(sp);
                }
                else
                {
                    sp.iSoLuong++;
                }
                return Redirect(url);
            }    
           
        }
        public ActionResult Tanglen(int ms)
        {
            List<Cart> lstGioHang = LayGioHang();
            Cart sp = lstGioHang.Find(n => n.iMasp == ms);
            var Thanhtien = sp.dThanhTien;
            if (sp.iSoLuong < 100)
            {
                sp.iSoLuong++;
                Thanhtien = sp.dThanhTien; 
            }
            return Content(string.Format("{0:#,##0,0}", Thanhtien));
        }
        public ActionResult GiamXuong(int ms)
        {
            List<Cart> lstGioHang = LayGioHang();
            Cart sp = lstGioHang.Find(n => n.iMasp == ms);
            var Thanhtien = sp.dThanhTien;
            if(sp.iSoLuong > 1)
            {
                sp.iSoLuong--;
                Thanhtien = sp.dThanhTien;
            }
            return Content(string.Format("{0:#,##0,0}", Thanhtien));
        }

        
        private int TongSoLuong()
        {
            int iTongSoLuong = 0;
            List<Cart> lstGioHang = Session["Cart"] as List<Cart>;
            if (lstGioHang != null)
            {
                iTongSoLuong = lstGioHang.Sum(n => n.iSoLuong);

            }
            return iTongSoLuong;
        }
        private double TongTien()
        {
            double dTongTien = 0;
            List<Cart> lstGioHang = Session["Cart"] as List<Cart>;
            if (lstGioHang != null)
            {
                dTongTien = lstGioHang.Sum(n => n.dThanhTien);
            }
            //ViewBag.TongSoLuong = TongSoLuong();
            //ViewBag.TongTien = TongTien();
            //ViewBag.TongTiencoship = TongTien() + 32000;
            return dTongTien;
        }
        
        public ActionResult hehe()
        {
            double dTongTien = 0;
            dTongTien = TongTien();
            return Content(string.Format("{0:#,##0,0}", dTongTien));
        }
        public ActionResult GioHang()
        {
            List<Cart> lstGioHang = LayGioHang();
            if (lstGioHang.Count == 0)
            {
                return RedirectToAction("Product", "Mercuryshop");
                //return RedirectToAction("GioHang", "ShopCart");
            }
            ViewBag.TongSoLuong = TongSoLuong();
            ViewBag.TongTien = TongTien();
            return View(lstGioHang);
        }
        public ActionResult GioHangPartial()
        {
            ViewBag.TongSoLuong = TongSoLuong();
            ViewBag.TongTien = TongTien();
            return PartialView();
        }

        public ActionResult XoaSPKhoiGioHang(int iMasp)
        {
            List<Cart> lstGioHang = LayGioHang();
            Cart sp = lstGioHang.SingleOrDefault(n => n.iMasp == iMasp);
            if (sp != null)
            {
                lstGioHang.RemoveAll(n => n.iMasp == iMasp);
                if (lstGioHang.Count == 0)
                {
                    return RedirectToAction("Index", "Mercuryshop");
                }
            }
            return RedirectToAction("GioHang");
        }

        public ActionResult CapNhatGioHang(int iMasp, FormCollection f)
        {
            List<Cart> lstGioHang = LayGioHang();
            Cart sp = lstGioHang.SingleOrDefault(n => n.iMasp == iMasp);
            if (sp != null)
            {
                sp.iSoLuong = int.Parse(f["txtSoLuong"].ToString());
            }
            return RedirectToAction("Cart");
        }
        public ActionResult XoaGioHang()
        {
            List<Cart> lstGioHang = LayGioHang();
            lstGioHang.Clear();
            return RedirectToAction("Index", "Mercuryshop");
        }

        public List<Cart> LayDsSpThanhToan()
        {
            List<Cart> lstSPThanhToan = Session["DSThanhToan"] as List<Cart>;
            if (lstSPThanhToan == null)
            {
                lstSPThanhToan = new List<Cart>();
                Session["DSThanhToan"] = lstSPThanhToan;
            }
            return lstSPThanhToan;
        }

        [HttpPost]
        public ActionResult Taodstt(List<int> selectedValues)
        {
            double dTongTien = 0;
            Session["DSThanhToan"] = null;
            List<Cart> lstSPThanhToan = LayDsSpThanhToan();
            List<Cart> lstGioHang = LayGioHang();
            if (selectedValues != null)
            {
                foreach (var id in selectedValues)
                {
                    Cart sp = lstGioHang.Find(n => n.iMasp == id);
                    lstSPThanhToan.Add(sp);
                }
            }
            dTongTien = TongTien();
            return Content(string.Format("{0:#,##0,0}", dTongTien));
        }

        private double TongTienDSTT()
        {
            
            double dTongTien = 0;
            List<Cart> lstSPThanhToan = Session["DSThanhToan"] as List<Cart>;
            if (lstSPThanhToan != null)
            {
                dTongTien = lstSPThanhToan.Sum(n => n.dThanhTien);
            }
            //ViewBag.TongSoLuong = TongSoLuong();
            //ViewBag.TongTien = TongTien();
            //ViewBag.TongTiencoship = TongTien() + 32000;
            return dTongTien;
        }

        [HttpPost]
        public ActionResult DatHang(List<int> selectedValues)
        {
            //if (Session["TaiKhoan"] == null || Session["TaiKhoan"].ToString() == "")
            //{
            //    return RedirectToAction("DangNhap", "Customer");
            //}
            //if (Session["Cart"] == null)
            //{
            //    return RedirectToAction("Product", "Mercuryshop");
            //}
            Session["DSThanhToan"] = null;
            List<Cart> lstSPThanhToan = LayDsSpThanhToan();
            List<Cart> lstGioHang = LayGioHang();
            
            //Session["Cart"] = null;
            if (selectedValues != null)
            {
                foreach (var id in selectedValues)
                {
                    Cart sp = lstGioHang.Find(n => n.iMasp == id);
                    lstSPThanhToan.Add(sp);
                }
            }
            
            //List<Cart> lstGioHang = LayGioHang();
            return View("DatHang", lstSPThanhToan);
        }

        [HttpGet]
        public ActionResult DatHang()
        {
            List<Cart> lstSPThanhToan = LayDsSpThanhToan();
            ViewBag.TongSoLuong = TongSoLuong();
            ViewBag.TongTien = TongTienDSTT();
            ViewBag.TongTiencoship = TongTienDSTT() + 32000;
            return View(lstSPThanhToan);
        }
        [HttpPost]
        public ActionResult Dat(FormCollection f)
        {
            DonHang dh = new DonHang();
            Customer kh = (Customer)Session["TaiKhoan"];
            List<Cart> lstGioHang = LayGioHang();
            List<Cart> lstSPThanhToan = LayDsSpThanhToan();
            dh.Customer_Id = kh.Customer_Id;
            dh.NgayDat = DateTime.Now;
            dh.NgayGiao = DateTime.Now;
            dh.TinhTrangGiaoHang = true;
            dh.TinhTrangThanhToan = false;
            db.DonHangs.Add(dh);
            db.SaveChanges();
            //foreach (var item in lstGioHang)
            //{
            //    CTDonHang ctdh = new CTDonHang();
            //    ctdh.MaDonHang = dh.MaDonHang;
            //    ctdh.Product_Id = item.iMasp;
            //    ctdh.SoLuong = item.iSoLuong;
            //    ctdh.DonGia = (decimal)item.dDonGia;
            //    db.CTDonHangs.Add(ctdh);
            //}
            //db.SaveChanges();
            Session["Cart"] = null;
            ViewBag.mess = "Đặt hàng thành công";
            return RedirectToAction("Index", "Mercuryshop");
        }
        public ActionResult XacNhanDonHang()
        {
            return View();
        }
        // GET: ShoppingCart
        public ActionResult Index()
        {
            return View();
        }
    }
}

Views/Customer/DangKy.cshtml
@{
    ViewBag.Title = "DangKy";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}

<section class="banner-area organic-breadcrumb">
    <div class="container">
        <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
            <div class="col-first">
                <h1>Đăng ký tài khoản</h1>
                <nav class="d-flex align-items-center">
                    <a href="@Url.Action("Index", "Mercuryshop")">Trang chủ<span class="lnr lnr-arrow-right"></span></a>
                    <a href="@Url.Action("GioHang", "ShopCart")">Giỏ Hàng</a>
                </nav>
            </div>
        </div>
    </div>
</section>
<!-- End Banner Area -->
<!--================Login Box Area =================-->
<section class="login_box_area section_gap">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="login_box_img">
                    <img class="img-fluid" style="height:500px;" src="~/Content/Theme/img/logindn.jpg" alt="">
                    <div class="hover">
                        <h4>Thành viên mới</h4>
                        <p>Nếu bạn đã có tài khoản bạn có thể đăng nhập ngay vào trang web để khám phá thêm về cửa hàng</p>
                        <a class="primary-btn" href="@Url.Action("DangNhap","Customer")">Đăng nhập</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div style="padding-top: 15px;" class="login_form_inner">
                    <h3>Thông tin tài khoản</h3>
                    @using (Html.BeginForm(new { @onchange = "this.form.submit();", @class = "row login_form" }))
                    {
                        <div class="col-md-12 form-group">
                            <input type="text" class="form-control" id="name" name="Email" placeholder="Email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Email'">
                        </div>
                        <div class="col-md-12 form-group">
                            <input type="text" class="form-control" id="name" name="Name" placeholder="Họ và tên" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Họ và tên'">
                        </div>
                        <div class="col-md-12 form-group">
                            <input type="tel" class="form-control" id="name" name="Numberphone" placeholder="Số điện thoại" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Số điện thoại'">
                        </div>
                        <div class="col-md-12 form-group">
                            <input type="password" class="form-control" id="name" name="Pass" placeholder="Mật khẩu" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Password'">
                        </div>
                        <div class="col-md-12 form-group">
                            <input type="password" class="form-control" id="name" name="rePass" placeholder="Nhập lại mật khẩu" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Password'">
                        </div>
                        <div class="col-md-12 form-group">
                            <input type="text" class="form-control" id="name" name="Address" placeholder="Địa chỉ" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Địa chỉ'">
                        </div>
                        <div class="col-md-12 form-group">
                            <button style="width:250px; height:50px" type="submit" value="submit" class="primary-btn">Đăng ký</button>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>

Views/Customer/DangNhap.cshtml
@{
    ViewBag.Title = "DangNhap";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}

<section class="banner-area organic-breadcrumb">
    <div class="container">
        <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
            <div class="col-first">
                <h1>Đăng nhập tài khoản</h1>
                <nav class="d-flex align-items-center">
                    <a href="@Url.Action("Index", "Mercuryshop")">Trang chủ<span class="lnr lnr-arrow-right"></span></a>
                    <a href="@Url.Action("Product", "Mercuryshop")">Sản phẩm</a>
                </nav>
            </div>
        </div>
    </div>
</section>
<!-- End Banner Area -->
<!--================Login Box Area =================-->
<section class="login_box_area section_gap">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="login_box_img">
                    <img class="img-fluid" style="height:500px;" src="~/Content/Theme/img/logindn.jpg" alt="">
                    <div class="hover">
                        <h4>Khách hàng mới</h4>
                        <p>Nếu chưa có tài khoản bạn có thể đăng ký ngay để xem và đặt mua các sản phẩm từ cửa hàng của chúng tôi</p>
                        <a class="primary-btn" href="@Url.Action("DangKy", "Customer")">Tạo tài khoản mới</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div style="padding-top: 100px;" class="login_form_inner">
                    <h3>Nhập thông tin</h3>
                    @using (Html.BeginForm(new { @onchange = "this.form.submit();", @class = "row login_form" }))
                    {
                        <div class="col-md-12 form-group">
                            <input type="text" class="form-control" id="name" name="Email" placeholder="Email/Số điện thoại" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Email/SĐT'">
                        </div>
                        <div></div>
                        <div class="col-md-12 form-group">
                            <input type="password" class="form-control" id="name" name="Pass" placeholder="Mật khẩu" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Password'">
                        </div>
                        @ViewBag.ThongBao
                        <div class="col-md-12 form-group">
                            <button style="width: 250px; height: 50px" type="submit" value="submit" class="primary-btn">Đăng nhập</button>
                        </div>
                        <h6 href="#" style="color: #337ab7;">Quên mật khẩu?</h6>
                        <h6><a href="@Url.Action("DangNhap","UserAdmin", new { Area = "Admin"})" style="color: #337ab7;">Quản trị viên</a></h6>
                    }
                </div>
            </div>
        </div>
    </div>
</section>

Views/Customer/RequestResetPX.cshtml
@{
    ViewBag.Title = "RequestResetPX";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}

<h2>RequestResetPX</h2>
<div class="container">
    <nav class="biolife-nav">
        <ul>
            <li class="nav-item">
                <a href="index-2.html" class="permal-link">Home</a>
            </li>
            <li class="nav-item">
                <span class="current-page">Authentication</span>
            </li>
        </ul>
    </nav>
</div>

<div class="page-contain login-page">
    <!-- Main content -->
    <div id="main-content" class="main-content">
        <div class="container">
            <div class="row">
                <!--Form Sign In-->
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12"
                     style="display: flex;
                            justify-content: center;
                            align-items: center;
                 ">
                    <div class="signin-container"
                         style="width: 480px;
                                border-radius: 10px;
                                box-shadow: 0 14px 28px rgba(0, 0, 0, 0.25),0 10px 10px rgba(0, 0, 0, 0.22);
                                z-index: 1;
                                overflow: hidden;
                                margin: 80px;
                                padding: 50px 30px;
                     ">

                        <p class="title" style="margin-bottom: 40px">
                            Đặt Lại Mật Khẩu
                        </p>

                        @using (Html.BeginForm(new { name = "frm-login" }))
                        {
                            <p class="form-row">
                                <label for="fid-name">Email:<span class="requite">*</span></label>
                                <input type="text"
                                       id="fid-name"
                                       name="Email"
                                       value=""
                                       class="txt-input"/>
                            </p>
                            if (@ViewBag.ThongBao == "1")
                            {
                                <p style="color: #379237;"><img src="~/Theme/assets/images/icon/check.png" style="height: 18px; margin-right: 5px;" alt="">một liên kết đổi lại mật khẩu đã được gửi vào mail của bạn</p>
                            }
                            if (@ViewBag.ThongBao == " ")
                            {
                                <p style="color: #ea2d3f;"><img src="~/Theme/assets/images/icon/erorr.png" style="height: 18px; margin-right: 5px;" alt="">không tìm thấy tài khoản</p>
                            }
                            <p class="form-row wrap-btn" style="text-align: center">
                                <a class="btn btn-submit btn-bold cancelbtnP"
                                   type="submit"
                                   style="border: #379237 1px solid; color: #379237;">
                                   Hủy
                                </a>

                                <button class="btn btn-submit btn-bold"
                                        type="submit"
                                        style="margin-left: 150px">
                                    Tiếp Theo
                                </button>
                            </p>
                            <p style="text-align: center;
                                      margin-top: 20px;
                                      color: #ffffff;
                                      text-transform: uppercase;
                                      border: none;
                                      border-radius: 9999px;
                                      text-align: center;
                                      font-weight: 700;">
                            </p>
                        }

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>